### ISSUE TITLE
Some errors in output when searching for accented words

### ISSUE THREAD

**Issue by hiperjp** [Mottl/GetOldTweets3#15]
Hi Mottl, thanks to come alive again this scripts.

I am here for a possible bug (or misunderstanding) when searching for accented words. Please take a look to my log.

```
I, [2018-12-14T11:46:09.782525 #4968]  INFO -- :  - Processing Term: Caja de compensación 18
I, [2018-12-14T11:46:09.782637 #4968]  INFO -- :    CMD: /bin/bash -l -c 'cd ~/venv/get-old-tweets3_mottl && source bin/activate && GetOldTweets3 --output "/home/ubuntu/artool-utils/releases/20181207142540/public/dl/Twitter_20181214-084609_750-#2.csv" --querysearch "Caja de compensación 18" --since "2018-12-11" --until "2018-12-15"'
I, [2018-12-14T11:46:10.055077 #4968]  INFO -- pid 5243 exit 0: Downloading tweets...
Traceback (most recent call last):
  File "/home/ubuntu/venv/get-old-tweets3_mottl/bin/GetOldTweets3", line 171, in main
    got.manager.TweetManager.getTweets(tweetCriteria, receiveBuffer, debug=debug)
  File "/home/ubuntu/venv/get-old-tweets3_mottl/lib/python3.5/site-packages/GetOldTweets3/manager/TweetManager.py", line 65, in getTweets
    json = TweetManager.getJsonReponse(tweetCriteria, refreshCursor, cookieJar, proxy, user_agent, debug=debug)
  File "/home/ubuntu/venv/get-old-tweets3_mottl/lib/python3.5/site-packages/GetOldTweets3/manager/TweetManager.py", line 180, in getJsonReponse
    url = url % (urllib.parse.quote(urlGetData.strip()), urlLang, urllib.parse.quote(refreshCursor))
  File "/usr/lib/python3.5/urllib/parse.py", line 706, in quote
    string = string.encode(encoding, errors)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc3' in position 18: surrogates not allowed

'utf-8' codec can't encode character '\udcc3' in position 18: surrogates not allowed

Done. Output file generated "/home/ubuntu/artool-utils/releases/20181207142540/public/dl/Twitter_20181214-084609_750-#2.csv".

I, [2018-12-14T11:46:10.055220 #4968]  INFO -- :  - Processing Term: Caja de compensacion 18
I, [2018-12-14T11:46:10.055336 #4968]  INFO -- :    CMD: /bin/bash -l -c 'cd ~/venv/get-old-tweets3_mottl && source bin/activate && GetOldTweets3 --output "/home/ubuntu/artool-utils/releases/20181207142540/public/dl/Twitter_20181214-084609_750-#3.csv" --querysearch "Caja de compensacion 18" --since "2018-12-11" --until "2018-12-15"'
I, [2018-12-14T11:46:10.491267 #4968]  INFO -- pid 5337 exit 0: Downloading tweets...

Done. Output file generated "/home/ubuntu/artool-utils/releases/20181207142540/public/dl/Twitter_20181214-084609_750-#3.csv".
```

As you can see the term "Caja de compensación 18" has an accented "ó" wich is giving the mentioned error backtrace. while the other term is fine.

Anyway, the tweets seem to be downloaded just fine too.

**Comment by Mottl** [comment]
Weird...
I can't reproduce your error:
```sh
./GetOldTweets3 --querysearch "Caja de compensación 18" --maxtweets 20
Downloading tweets...
Saved 20
Done. Output file generated "output_got.csv".
```

May be you have a local issue with UTF8 symbols in your terminal?

```sh
echo "Caja de compensación 18" | md5
ce3dd0bf782257367eaf7e1b3d207248
```

**Comment by Mottl** [comment]
No answer from reporter received. Closed.

**Comment by hiperjp** [comment]
Hi Mottl, sorry for late answer. I have same md5 checksum:

echo "Caja de compensación 18" | md5sum
ce3dd0bf782257367eaf7e1b3d207248

But same errors until today:
```
    CMD Executed: /bin/bash -l -c 'cd ~/venv/get-old-tweets3_mottl && source bin/activate && GetOldTweets3 --output "/home/ubuntu/artool-utils/releases/20190412181531/public/dl/20190415162652_KwSearch_20190401-20190415_S3777-#1.csv" --querysearch "Corporación Capacitación Construcción " --since 2019-04-01 --until 2019-04-16 --lang es'
 Downloading tweets...
Traceback (most recent call last):
  File "/home/ubuntu/venv/get-old-tweets3_mottl/bin/GetOldTweets3", line 171, in main
    got.manager.TweetManager.getTweets(tweetCriteria, receiveBuffer, debug=debug)
  File "/home/ubuntu/venv/get-old-tweets3_mottl/lib/python3.5/site-packages/GetOldTweets3/manager/TweetManager.py", line 65, in getTweets
    json = TweetManager.getJsonReponse(tweetCriteria, refreshCursor, cookieJar, proxy, user_agent, debug=debug)
  File "/home/ubuntu/venv/get-old-tweets3_mottl/lib/python3.5/site-packages/GetOldTweets3/manager/TweetManager.py", line 180, in getJsonReponse
    url = url % (urllib.parse.quote(urlGetData.strip()), urlLang, urllib.parse.quote(refreshCursor))
  File "/usr/lib/python3.5/urllib/parse.py", line 706, in quote
    string = string.encode(encoding, errors)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc3' in position 9: surrogates not allowed

'utf-8' codec can't encode character '\udcc3' in position 9: surrogates not allowed

Done. Output file generated "/home/ubuntu/artool-utils/releases/20190412181531/public/dl/20190415162652_KwSearch_20190401-20190415_S3777-#1.csv".
  - Going to retrieve 0 statuses.
```

But if i execute the command in console:

`/bin/bash -l -c 'cd ~/venv/get-old-tweets3_mottl && source bin/activate && GetOldTweets3 --output "/home/ubuntu/artool-utils/releases/20190412181531/public/dl/20190415162652_KwSearch_20190401-20190415_S3777-#1.csv" --querysearch "Corporación Capacitación Construcción " --since 2019-04-01 --until 2019-04-16 --lang es'`

There is 1 tweet which is correct.
