### ISSUE TITLE
Error when getting tweets (NoneType object)

### ISSUE THREAD

**Issue by stvncao5** [Mottl/GetOldTweets3#61]
I think this bug has something to do with the latest workaround from #49 (concerning hashtags with only emoticons).

Here's the error:
```
Traceback (most recent call last):
  File "C:\Users\admin user\Downloads\tweets_collection.py", line 117, in <module>
    search_1 = gets_tweets('Bernie Sanders', 1000, truncated_date_list[i], truncated_date_list[i+1])
  File "C:\Users\admin user\Downloads\tweets_collection.py", line 28, in gets_tweets
    list_of_tweets = got.manager.TweetManager.getTweets(tweetCriteria)
  File "C:\Users\admin user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\GetOldTweets3\manager\TweetManager.py", line 88, in getTweets
    rawtext = TweetManager.textify(tweetPQ("p.js-tweet-text").html(), tweetCriteria.emoji)
  File "C:\Users\admin user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\GetOldTweets3\manager\TweetManager.py", line 184, in textify
    html = html.replace("\n", puc)
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by jemielniak** [comment]
Running from the console, I've just starting getting a similar error:

`Traceback (most recent call last):
  File "/home/dariusz/anaconda3/bin/GetOldTweets3", line 209, in main
    got.manager.TweetManager.getTweets(tweetCriteria, receiveBuffer, debug=debug)
  File "/home/dariusz/anaconda3/lib/python3.7/site-packages/GetOldTweets3/manager/TweetManager.py", line 88, in getTweets
    rawtext = TweetManager.textify(tweetPQ("p.js-tweet-text").html(), tweetCriteria.emoji)
  File "/home/dariusz/anaconda3/lib/python3.7/site-packages/GetOldTweets3/manager/TweetManager.py", line 184, in textify
    html = html.replace("\n", puc)
AttributeError: 'NoneType' object has no attribute 'replace'
`

**Comment by gittyhubbycat** [comment]
@jemielniak I had the same problem as you, and I believe Anaconda is the problem. 

You have to rebuild your files after editing them, or use a different python environment.

Related: https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/ySj4Hl8zCks

**Comment by edwardslau** [comment]
@stvncao5 I have the exact same problem when looking into the exact same keyword! 
Here is the error:
```
Traceback (most recent call last):
  File "GetOldTweets3.py", line 47, in <module>
    import GetOldTweets3 as got
  File "/Users/xxx/Documents/Optimized-Modified-GetOldTweets3-OMGOT-master/GetOldTweets3-0.0.10/GetOldTweets3/__init__.py", line 2, in <module>
    from . import manager
  File "/Users/xxx/Documents/Optimized-Modified-GetOldTweets3-OMGOT-master/GetOldTweets3-0.0.10/GetOldTweets3/manager/__init__.py", line 2, in <module>
    from .TweetManager import TweetManager
  File "/Users/xxx/Documents/Optimized-Modified-GetOldTweets3-OMGOT-master/GetOldTweets3-0.0.10/GetOldTweets3/manager/TweetManager.py", line 5, in <module>
    from pyquery import PyQuery
ModuleNotFoundError: No module named 'pyquery'
```
When I run it with `
python3.6 GetOldTweets3.py --querysearch "Bernie Sanders"--since 2020-03-16 --until 2020-03-23 -- lang es -- maxtweets 10000 `
and I get  
 ```
File "GetOldTweets3.py", line 172
    nonlocal cnt
               ^
SyntaxError: invalid syntax
```
when I run it with `python GetOldTweets3.py --querysearch "Bernie Sanders"--since 2020-03-16 --until 2020-03-23 -- lang es -- maxtweets 10000`
Needing help ASAP!
