### ISSUE TITLE
Problem iterating through multiple days and storing output because of high amount of daily tweets

### ISSUE THREAD

**Issue by PaulNoo** [Mottl/GetOldTweets3#92]
Hi all,

I've got an issue extracting a set of tweets over a certain date range. The number of tweets per day is quite high so my idea was to extract the tweets one day at a time and repeat this three times for every day since sometimes the download halts at around 10k tweets on a day. I can't figure out how to store the tweets for one day in a unique csv without interfering with the formatting.

My ideal solution would look like this:
For a specific date I would get three different csv files, which is iterated in a period specified in the since and until date (bottom of the script). It's probably a fairly easy solution but it's driving me crazy for days now.

An extra amazing solution would be if the process is iterated for a range of different search terms like "bitcoin", "btc" etc.. This is however not as important, so if there's no easy solution please ignore this :)

I've been using some modified code I found in one of the previous issues, which I posted below:

    import GetOldTweets3 as got
    import time
    import pandas as pd
    from datetime import datetime, timedelta

     DownloadTweets(SinceDate, UntilDate, query, sleep=900) :
    #create a list of day numbers
    since = datetime.strptime(SinceDate, '%Y-%m-%d')
    days = list(range(0, (datetime.strptime(UntilDate, '%Y-%m-%d') - datetime.strptime(SinceDate, '%Y-%m-%d')).days+1))
    tweets = []
  
        for day in days:
        init = got.manager.TweetCriteria().setQuerySearch(query).setSince((since + timedelta(days=day)).strftime('%Y-%m-%d')).setUntil((since+ timedelta(days=day+1)).strftime('%Y-%m-%d'))
        get = got.manager.TweetManager.getTweets(init)
        tweets.append([[tweet.id, tweet.date, tweet.text] for tweet in get])
        print("day", day+1, "of", len(days), "completed")
        print("sleeping for", sleep, "seconds")
        time.sleep(sleep)
    #flatten list
    tweets = [tweet for sublist in tweets for tweet in sublist]
    return tweets

    #%%
    since = "2020-07-01"
    until = "2020-07-04"

    
    tweets = DownloadTweets(since, until, query='bitcoin', sleep=30)
        
    df_1 = pd.DataFrame.from_records(tweets)
    df_1.to_csv("%s.csv" % since)    

This however does not work as I envisioned and combines all days in one csv file and does not iterate the process three times.

If somebody could maybe help me with this or point me in the right direction I would be extremely grateful.

Thanks in advance!
Paul

**Comment by PaulNoo** [comment]
I think I got it nearly figured out. I'm also working with the twint package to collect tweets and using 'day' as a variable to store different csv files works in that case. Working with this library gives me the following error:

day 1 of 9 completed
sleeping for 1 seconds
Traceback (most recent call last):
  File "/Users/Paul/Downloads/testing got.py", line 34, in <module>
    DownloadTweets(since, until, query, sleep)
  File "/Users/Paul/Downloads/testing got.py", line 27, in DownloadTweets
    df = pd.DataFrame.from_records(tweets)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 1636, in from_records
    arrays, arr_columns = to_arrays(data, columns, coerce_float=coerce_float)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 484, in to_arrays
    data = [tuple(x) for x in data]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 484, in <listcomp>
    data = [tuple(x) for x in data]
TypeError: 'datetime.datetime' object is not iterable


```
import GetOldTweets3 as got
import time
import pandas as pd
from datetime import datetime, timedelta


#%%
since = "2020-07-01"
until = "2020-07-10"

query = "stellar lumen"

sleep = 1

def DownloadTweets(SinceDate, UntilDate, query, sleep=900) :
    #create a list of day numbers
    since = datetime.strptime(SinceDate, '%Y-%m-%d')
    days = list(range(1, (datetime.strptime(UntilDate, '%Y-%m-%d') - datetime.strptime(SinceDate, '%Y-%m-%d')).days+1))
    tweets = []
  
    for day in days:
        init = got.manager.TweetCriteria().setQuerySearch(query).setSince((since + timedelta(days=day)).strftime('%Y-%m-%d')).setUntil((since+ timedelta(days=day+1)).strftime('%Y-%m-%d'))
        get = got.manager.TweetManager.getTweets(init)
        tweets.append([[tweet.id, tweet.date, tweet.text] for tweet in get])
        #flatten list
        tweets = [tweet for sublist in tweets for tweet in sublist]
        df = pd.DataFrame.from_records(tweets)
        df.to_csv("%s.2020-07-%d_1.csv" % (query, day))
        print("day", day, "of", len(days), "completed")
        print("sleeping for", sleep, "seconds")
        time.sleep(sleep)
       

DownloadTweets(since, until, query, sleep)
      
```

Anyone that knows what's going on here? Been browsing all day but I can't figure it out...
